### ISSUE TITLE
does not work for 2560 monitors 

### ISSUE THREAD

**Issue by kirillp** [4rtzel/poe-archnemesis-scanner#61]
Tried latest version 2.2
I also tried  to directly set window location

`poe_arch_scanner.exe --scanner-window-x 112 --scanner-window-y 383 --scanner-window-width 640 --scanner-window-height 640`

**Comment by 4rtzel** [comment]
I'm also running the game on 2560x1440 and it works fine for me. What does --show-capture-image display? What's your image scaling?

**Comment by kirillp** [comment]
default it set to Scanner window: x=88, y=316, width=362, height=362
which is not  correct, the window is about (112,383) wh=( 640  640)

IF I set imagescale to 0.8461 it crash with 

Missing Items: []
Exception in Tkinter callback

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "UIOverlay.py", line 87, in _scan
  File "ImageScanner.py", line 79, in scan
IndexError: list index out of range

 > What does --show-capture-image display?

<img width="501" alt="2022-02-21 23_29_34-{C__Games_poe_arch_scanner} - Far 3 0 5151 x64" src="https://user-images.githubusercontent.com/4068190/155022527-42b24324-ff95-4d75-99d5-4d3375112789.png">

**Comment by 4rtzel** [comment]
That's very strange. Are you playing PoE in windowed mode perchance? Does PoE have the same resolution as the monitor?

Could you try adjusting scanner-window-{x,y,width,height} so your scanner-capture-image would look like this: ![](https://i.imgur.com/XdWvR4j.png)

Also for 2560x1440 image scaling should be around 0.91.

**Comment by kirillp** [comment]
> Are you playing PoE in windowed mode perchance? 

I'm playing in a maximized window, the tool does not work for fill screen windowed as well

> Does PoE have the same resolution as the monitor?
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/4068190/155028137-a5339729-e0ac-41e9-a55c-d5102af45fca.png">

**Comment by kirillp** [comment]
> Could you try adjusting scanner-window-{x,y,width,height} so your scanner-capture-image would look like this:

`poe_arch_scanner.exe --scanner-window-x 144 --scanner-window-y 462 --scanner-window-width 540 --scanner-window-height 540 --show-capture-image`

<img width="407" alt="image" src="https://user-images.githubusercontent.com/4068190/155030606-0cfce887-8d56-4e62-9e86-a683cea0773c.png">


in that case I get 

```
Scanner window: x=144, y=462, width=540, height=540
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "UIOverlay.py", line 87, in _scan
  File "ImageScanner.py", line 79, in scan
IndexError: list index out of range
```

**Comment by Davst** [comment]
I'm also having issues on 1440p

Scans.. but shows absolutely nothing at all


![image](https://user-images.githubusercontent.com/3330933/155810810-9390edf6-fb92-46b0-b6d2-faaaf54eb2a5.png)

Log: 

`Scanner window: x=156, y=459, width=586, height=586
row=1, column=1 is empty
row=1, column=2 is empty
row=1, column=3 is empty
row=1, column=4 is empty
row=1, column=5 is empty
row=1, column=6 is empty
row=1, column=7 is empty
row=1, column=8 is empty
row=2, column=1 is empty
row=2, column=2 is empty
row=2, column=3 is empty
row=2, column=4 is empty
row=2, column=5 is empty
row=2, column=6 is empty
row=2, column=7 is empty
row=2, column=8 is empty
row=3, column=1 is empty
row=3, column=2 is empty
row=3, column=3 is empty
row=3, column=4 is empty
row=3, column=5 is empty
row=3, column=6 is empty
row=3, column=7 is empty
row=3, column=8 is empty
row=4, column=1 is empty
row=4, column=2 is empty
row=4, column=3 is empty
row=4, column=4 is empty
row=4, column=5 is empty
row=4, column=6 is empty
row=4, column=7 is empty
row=4, column=8 is empty
row=5, column=1 is empty
row=5, column=2 is empty
row=5, column=3 is empty
row=5, column=4 is empty
row=5, column=5 is empty
row=5, column=6 is empty
row=5, column=7 is empty
row=5, column=8 is empty
row=6, column=1 is empty
row=6, column=2 is empty
row=6, column=3 is empty
row=6, column=4 is empty
row=6, column=5 is empty
row=6, column=6 is empty
row=6, column=7 is empty
row=6, column=8 is empty
row=7, column=1 is empty
row=7, column=2 is empty
row=7, column=3 is empty
row=7, column=4 is empty
row=7, column=5 is empty
row=7, column=6 is empty
row=7, column=7 is empty
row=7, column=8 is empty
row=8, column=1 is empty
row=8, column=2 is empty
row=8, column=3 is empty
row=8, column=4 is empty
row=8, column=5 is empty
row=8, column=6 is empty
row=8, column=7 is empty
row=8, column=8 is empty
Items found: 0/64
Missing Items: ['Innocence-Touched', 'Brine King-Touched', 'Treant Horde', 'Tukohama-Touched', 'Abberath-Touched', 'Lunaris-Touched', 'Solaris-Touched', 'Mirror Image', 'Mana Siphoner', 'Ice Prison', 'Storm Strider', 'Heralding Minions', 'Toxic', 'Sentinel', 'Steel-Infused', 'Bonebreaker', 'Executioner', 'Magma Barrier', 'Flame Strider', 'Frenzied', 'Rejuvenating', 'Invulnerable', 'Frost Strider', 'Empowered Minions', 'Invulnerable', 'Magma Barrier', 'Empowered Minions', 'Echoist', 'Soul Conduit', 'Consecrator', 'Dynamo', 'Permafrost', 'Sentinel', 'Stormweaver', 'Hasted', 'Dynamo', 'Arcane Buffer', 'Frenzied', 'Berserker', 'Incendiary', 'Bonebreaker', 'Flameweaver', 'Hasted', 'Gargantuan', 'Vampiric', 'Sentinel', 'Juggernaut', 'Consecrator', 'Frostweaver', 'Hasted', 'Necromancer', 'Executioner', 'Gargantuan', 'Sentinel', 'Juggernaut', 'Consecrator', 'Incendiary', 'Bonebreaker', 'Necromancer', 'Executioner', 'Gargantuan', 'Bombardier', 'Overcharged', 'Frenzied', 'Berserker', 'Bombardier', 'Overcharged', 'Frenzied', 'Berserker']`
